### ISSUE TITLE
Frequancy State

### ISSUE THREAD

**Issue by nedimkivanc** [gutierrezps/ESP32_I2C_Slave#4]
Hello;

Thanks for the library, it works really well. In one of my projects, I need to communicate with stm32 to ı2c. I think I'm having problems with frequencies. I could not find a frequency arrangement in the library. Which frequency does it use for communication or can they change the frequency?

**Comment by gutierrezps** [comment]
The frequency of SCL line is dictated by the master device, not by the slave. The standard value is 100 kHz, but [there are other modes](https://en.wikipedia.org/wiki/I%C2%B2C#Differences_between_modes) such as fast (400 kHz) and high-speed (3.4 MHz).
